### PR TITLE
#2 improve the username sign up validation

### PR DESCRIPTION
**Pull request by bonapartbon**
I fixed and tested the issue. It works fine now.

### CODE REVIEW

**Comment by bonapartbon** [comment]
@tehseen01 you can see it here.
Thanks

**Review by tehseen01 — COMMENTED** [review]
Hi, thanks for your contribution. I have a few suggestions to improve the username sign up validation:

- You can use a more descriptive error message for the regex pattern, such as “Username can only contain lowercase letters, numbers, hyphens, dots and underscores”.
- You can use Yup.string().required(“Username is required”) instead of Yup.string().required(“*This field is required”), to make it clear which field is missing.
- Here is how the code would look like after applying these suggestions:
```username: Yup.string()
    .matches(/^[a-z0-9-._]+$/, "Username can only contain lowercase letters, numbers and  . _ -")
    .min(2)
    .max(25)
    .required("Username is required"),```

**Comment by bonapartbon** [comment]
> Hi, thanks for your contribution. I have a few suggestions to improve the username sign up validation:
> 
> * You can use a more descriptive error message for the regex pattern, such as “Username can only contain lowercase letters, numbers, hyphens, dots and underscores”.
> * You can use Yup.string().required(“Username is required”) instead of Yup.string().required(“*This field is required”), to make it clear which field is missing.
> * Here is how the code would look like after applying these suggestions:
> 
> ```
>     .matches(/^[a-z0-9-._]+$/, "Username can only contain lowercase letters, numbers and  . _ -")
>     .min(2)
>     .max(25)
>     .required("Username is required"),```
> ```

I made those changes. Thanks!

**Review by tehseen01 — APPROVED** [review]
Thanks for contributing

**Comment by bonapartbon** [comment]
> Thanks for contributing

Sure, I'll try to contribute more on your project.

**Pull request merged**
